### ISSUE TITLE
Error load info from StorageManager in DSM 5.2

### ISSUE THREAD

**Issue by stast1** [ProtoThis/python-synology#38]
Home Assistant 0.109.0b5

Logger: aiohttp.server
Source: components/synology_dsm/config_flow.py:221 
First occurred: 11:40:54 (1 occurrences) 
Last logged: 11:40:54

Error handling request
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 125, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 54, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 93, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 148, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 196, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/config_flow.py", line 115, in async_step_user
    _login_and_fetch_syno_info, api, otp_code
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/config_flow.py", line 221, in _login_and_fetch_syno_info
    storage = api.storage
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 289, in storage
    self._storage = SynoStorage(data)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/api/storage/storage.py", line 15, in __init__
    self.update(raw_data)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/api/storage/storage.py", line 20, in update
    self._data = raw_data["data"]
KeyError: 'data'
```

_Originally posted by @stast1 in https://github.com/ProtoThis/python-synology/issues/26#issuecomment-621069703_

**Comment by stast1** [comment]
My test:

GET:
```
http://nas.local:5000/webman/modules/StorageManager/storagehandler.cgi?action=load_info
```
Response:
```
{
   "disks" : [
      {
         "container" : {
            "order" : 0,
            "str" : "DS3615xs",
            "supportPwrBtnDisable" : false,
            "type" : "internal"
         },
         "device" : "/dev/sdg",
         "disable_secera" : false,
         "diskType" : "SATA",
         "erase_time" : 312,
         "firm" : "1AG01118",
         "has_system" : true,
         "id" : "sdg",
         "is4Kn" : false,
         "isSsd" : false,
         "is_erasing" : false,
         "longName" : "Диск 7",
         "model" : "HD154UI                 ",
         "name" : "Диск 7",
         "num_id" : 7,
         "order" : 7,
         "portType" : "normal",
         "serial" : "S1XWJ1MZ104273",
         "size_total" : "1500301910016",
         "smart_status" : "safe",
         "status" : "normal",
         "support" : false,
         "temp" : 33,
         "used_by" : "pool_3",
         "vendor" : "SAMSUNG "
      },
      {
         "container" : {
            "order" : 0,
            "str" : "DS3615xs",
            "supportPwrBtnDisable" : false,
            "type" : "internal"
         },
         "device" : "/dev/sdf",
         "disable_secera" : false,
         "diskType" : "SATA",
         "erase_time" : 322,
         "firm" : "1AQ10001",
         "has_system" : true,
         "id" : "sdf",
         "is4Kn" : false,
         "isSsd" : false,
         "is_erasing" : false,
         "longName" : "Диск 6",
         "model" : "HD204UI                 ",
         "name" : "Диск 6",
         "num_id" : 6,
         "order" : 6,
         "portType" : "normal",
         "serial" : "S2H7J9CB200727",
         "size_total" : "2000398934016",
         "smart_status" : "safe",
         "status" : "normal",
         "support" : false,
         "temp" : 36,
         "used_by" : "pool_2",
         "vendor" : "SAMSUNG "
      },
      {
         "container" : {
            "order" : 0,
            "str" : "DS3615xs",
            "supportPwrBtnDisable" : false,
            "type" : "internal"
         },
         "device" : "/dev/sde",
         "disable_secera" : false,
         "diskType" : "SATA",
         "erase_time" : 120,
         "firm" : "VT100-33",
         "has_system" : true,
         "id" : "sde",
         "is4Kn" : false,
         "isSsd" : false,
         "is_erasing" : false,
         "longName" : "Диск 5",
         "model" : "SP2504C                 ",
         "name" : "Диск 5",
         "num_id" : 5,
         "order" : 5,
         "portType" : "normal",
         "serial" : "S09QJ1GYA03414",
         "size_total" : "250059350016",
         "smart_status" : "safe",
         "status" : "normal",
         "support" : false,
         "temp" : 42,
         "used_by" : "pool_1",
         "vendor" : "SAMSUNG "
      },
      {
         "container" : {
            "order" : 0,
            "str" : "DS3615xs",
            "supportPwrBtnDisable" : false,
            "type" : "internal"
         },
         "device" : "/dev/sdb",
         "disable_secera" : false,
         "diskType" : "SATA",
         "erase_time" : 168,
         "firm" : "CT100-10",
         "has_system" : true,
         "id" : "sdb",
         "is4Kn" : false,
         "isSsd" : false,
         "is_erasing" : false,
         "longName" : "Диск 2",
         "model" : "HD403LJ                 ",
         "name" : "Диск 2",
         "num_id" : 2,
         "order" : 2,
         "portType" : "normal",
         "serial" : "S0NFJ1KP206717",
         "size_total" : "400088457216",
         "smart_status" : "safe",
         "status" : "normal",
         "support" : false,
         "temp" : 40,
         "used_by" : "pool_1",
         "vendor" : "SAMSUNG "
      },
      {
         "container" : {
            "order" : 0,
            "str" : "DS3615xs",
            "supportPwrBtnDisable" : false,
            "type" : "internal"
         },
         "device" : "/dev/sda",
         "disable_secera" : false,
         "diskType" : "SATA",
         "erase_time" : 70,
         "firm" : "0001EXM1",
         "has_system" : true,
         "id" : "sda",
         "is4Kn" : false,
         "isSsd" : false,
         "is_erasing" : false,
         "longName" : "Диск 1",
         "model" : "ST250LT020-1AE14C       ",
         "name" : "Диск 1",
         "num_id" : 1,
         "order" : 1,
         "portType" : "normal",
         "serial" : "W041GXTL",
         "size_total" : "250059350016",
         "smart_status" : "safe",
         "status" : "normal",
         "support" : false,
         "temp" : 34,
         "used_by" : "pool_1",
         "vendor" : "Seagate"
      }
   ],
   "env" : {
      "batchtask" : {
         "max_task" : 64,
         "remain_task" : 64
      },
      "bay_number" : "7",
      "ebox" : [],
      "fs_acting" : false,
      "is_space_actioning" : false,
      "isns" : {
         "address" : "",
         "enabled" : false
      },
      "isns_server" : "",
      "max_fs_bytes" : "118747255799808",
      "max_fs_bytes_high_end" : "219902325555200",
      "model_name" : "DS3615xs",
      "ram_enough_for_fs_high_end" : false,
      "ram_size" : 6,
      "ram_size_required" : 32,
      "settingSwap" : false,
      "showpooltab" : true,
      "status" : {
         "system_crashed" : false,
         "system_need_repair" : false
      },
      "support" : {
         "ebox" : true,
         "raid_cross" : true,
         "sysdef" : true
      },
      "unique_key" : "3197dca51f"
   },
   "hotSpares" : [],
   "iscsiLuns" : [],
   "iscsiTargets" : [],
   "ports" : [],
   "ssdCaches" : [],
   "storagePools" : [
      {
         "can_do" : {
            "delete" : true,
            "migrate" : {
               "to_raid1" : 3,
               "to_raid5" : 2,
               "to_raid5+spare" : "3-9999"
            },
            "raid_cross" : true
         },
         "container" : "internal",
         "device_type" : "basic",
         "disk_failure_number" : 0,
         "disks" : [ "sdg" ],
         "id" : "pool_3",
         "is_actioning" : false,
         "is_writable" : true,
         "maximal_disk_size" : "0",
         "minimal_disk_size" : "1495373643776",
         "num_id" : 3,
         "pool_child" : [
            {
               "id" : "volume_3",
               "size" : {
                  "total" : "1471743410176",
                  "used" : "874603900928"
               }
            }
         ],
         "pool_path" : "",
         "progress" : {
            "percent" : "-1",
            "step" : "none"
         },
         "size" : {
            "total" : "1495361650688",
            "used" : "1495361650688"
         },
         "space_path" : "/dev/vg3",
         "spares" : [],
         "status" : "normal",
         "suggestions" : [],
         "timebackup" : false,
         "vspace_can_do" : {
            "drbd" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            },
            "flashcache" : {
               "apply" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               },
               "remove" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               },
               "resize" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               }
            },
            "snapshot" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            }
         }
      },
      {
         "can_do" : {
            "delete" : true,
            "migrate" : {
               "to_raid1" : 3,
               "to_raid5" : 2,
               "to_raid5+spare" : "3-9999"
            },
            "raid_cross" : true
         },
         "container" : "internal",
         "device_type" : "basic",
         "disk_failure_number" : 0,
         "disks" : [ "sdf" ],
         "id" : "pool_2",
         "is_actioning" : false,
         "is_writable" : true,
         "maximal_disk_size" : "0",
         "minimal_disk_size" : "1995470667776",
         "num_id" : 2,
         "pool_child" : [
            {
               "id" : "volume_2",
               "size" : {
                  "total" : "1963989639168",
                  "used" : "1905303121920"
               }
            }
         ],
         "pool_path" : "",
         "progress" : {
            "percent" : "-1",
            "step" : "none"
         },
         "size" : {
            "total" : "1995456905216",
            "used" : "1995456905216"
         },
         "space_path" : "/dev/vg2",
         "spares" : [],
         "status" : "normal",
         "suggestions" : [],
         "timebackup" : false,
         "vspace_can_do" : {
            "drbd" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            },
            "flashcache" : {
               "apply" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               },
               "remove" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               },
               "resize" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               }
            },
            "snapshot" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            }
         }
      },
      {
         "can_do" : {
            "data_scrubbing" : true,
            "delete" : true,
            "expand_by_disk" : 1,
            "raid_cross" : true
         },
         "container" : "internal",
         "device_type" : "shr_with_1_disk_protect",
         "disk_failure_number" : 0,
         "disks" : [ "sda", "sdb", "sde" ],
         "id" : "pool_1",
         "is_actioning" : false,
         "is_writable" : true,
         "maximal_disk_size" : "0",
         "minimal_disk_size" : "249953402880",
         "num_id" : 1,
         "pool_child" : [
            {
               "id" : "volume_1",
               "size" : {
                  "total" : "482379890688",
                  "used" : "83747680256"
               }
            }
         ],
         "pool_path" : "",
         "progress" : {
            "percent" : "-1",
            "step" : "none"
         },
         "size" : {
            "total" : "490221862912",
            "used" : "490221862912"
         },
         "space_path" : "/dev/vg1",
         "spares" : [],
         "status" : "normal",
         "suggestions" : [],
         "timebackup" : false,
         "vspace_can_do" : {
            "drbd" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            },
            "flashcache" : {
               "apply" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               },
               "remove" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               },
               "resize" : {
                  "can_do" : false,
                  "errCode" : 768,
                  "stopService" : false
               }
            },
            "snapshot" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            }
         }
      }
   ],
   "success" : true,
   "volumes" : [
      {
         "cacheStatus" : "",
         "can_do" : {
            "delete" : true
         },
         "container" : "internal",
         "device_type" : "basic",
         "disk_failure_number" : 0,
         "disks" : [ "sdg" ],
         "eppool_used" : "40960",
         "fs_type" : "ext4",
         "id" : "volume_3",
         "is_acting" : false,
         "is_actioning" : false,
         "is_inode_full" : false,
         "is_writable" : true,
         "max_fs_size" : "1152921504606846976",
         "num_id" : 3,
         "pool_path" : "pool_3",
         "progress" : {
            "percent" : "-1",
            "step" : "none"
         },
         "size" : {
            "free_inode" : "91271157",
            "total" : "1471743410176",
            "total_device" : "1495349067776",
            "total_inode" : "91275264",
            "used" : "874603900928"
         },
         "ssd_trim" : {
            "support" : "not support"
         },
         "status" : "normal",
         "suggestions" : [],
         "timebackup" : false,
         "used_by_gluster" : false,
         "vol_path" : "/volume3",
         "vspace_can_do" : {
            "drbd" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            },
            "flashcache" : {
               "apply" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : true
               },
               "remove" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : false
               },
               "resize" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : false
               }
            },
            "snapshot" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            }
         }
      },
      {
         "cacheStatus" : "",
         "can_do" : {
            "delete" : true
         },
         "container" : "internal",
         "device_type" : "basic",
         "disk_failure_number" : 0,
         "disks" : [ "sdf" ],
         "eppool_used" : "40960",
         "fs_type" : "ext4",
         "id" : "volume_2",
         "is_acting" : false,
         "is_actioning" : false,
         "is_inode_full" : false,
         "is_writable" : true,
         "max_fs_size" : "1152921504606846976",
         "num_id" : 2,
         "pool_path" : "pool_2",
         "progress" : {
            "percent" : "-1",
            "step" : "none"
         },
         "size" : {
            "free_inode" : "121793851",
            "total" : "1963989639168",
            "total_device" : "1995444322304",
            "total_inode" : "121798656",
            "used" : "1905303121920"
         },
         "ssd_trim" : {
            "support" : "not support"
         },
         "status" : "normal",
         "suggestions" : [],
         "timebackup" : false,
         "used_by_gluster" : false,
         "vol_path" : "/volume2",
         "vspace_can_do" : {
            "drbd" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            },
            "flashcache" : {
               "apply" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : true
               },
               "remove" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : false
               },
               "resize" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : false
               }
            },
            "snapshot" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            }
         }
      },
      {
         "cacheStatus" : "",
         "can_do" : {
            "delete" : true
         },
         "container" : "internal",
         "device_type" : "shr_with_1_disk_protect",
         "disk_failure_number" : 0,
         "disks" : [ "sda", "sdb", "sde" ],
         "eppool_used" : "200704",
         "fs_type" : "ext4",
         "id" : "volume_1",
         "is_acting" : false,
         "is_actioning" : false,
         "is_inode_full" : false,
         "is_writable" : true,
         "max_fs_size" : "1152921504606846976",
         "num_id" : 1,
         "pool_path" : "pool_1",
         "progress" : {
            "percent" : "-1",
            "step" : "none"
         },
         "size" : {
            "free_inode" : "29871677",
            "total" : "482379890688",
            "total_device" : "490209280000",
            "total_inode" : "29925376",
            "used" : "83747680256"
         },
         "ssd_trim" : {
            "support" : "not support"
         },
         "status" : "normal",
         "suggestions" : [],
         "timebackup" : false,
         "used_by_gluster" : false,
         "vol_path" : "/volume1",
         "vspace_can_do" : {
            "drbd" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            },
            "flashcache" : {
               "apply" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : true
               },
               "remove" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : false
               },
               "resize" : {
                  "can_do" : true,
                  "errCode" : 0,
                  "stopService" : false
               }
            },
            "snapshot" : {
               "resize" : {
                  "can_do" : false,
                  "errCode" : 53504,
                  "stopService" : false
               }
            }
         }
      }
   ]
}

```

**Comment by stast1** [comment]
I can still test, just tell me the necessary queries.
