### ISSUE TITLE
Unable to communicate with device

### ISSUE THREAD

**Issue by raman325** [ProtoThis/python-synology#41]
I am unable to communicate with my Diskstation with the latest update to 0.109 in HA. The last known working version of this module was 0.5.0. I am trying to talk to a DS 1817+. I use a custom subdomain with a reverse proxy, but since I am on my local network I tried through the reverse proxy as well as bypassing the reverse proxy and hitting the server directly. I tried calling the API through this package directly and I get the following debug + traceback logs:
```bash
DEBUG: Request params: {'api': 'SYNO.API.Info', 'version': 1, 'method': 'query'}
DEBUG: Request url: http://<HOST>:<PORT>/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query
DEBUG: Request status_code: 400
DEBUG: Request headers: {'Server': 'nginx', 'Date': 'Thu, 30 Apr 2020 05:56:35 GMT', 'Content-Type': 'text/html', 'Content-Length': '248', 'Connection': 'close'}
Traceback (most recent call last):
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 249, in _execute_request
    raise RequestException(resp)
requests.exceptions.RequestException: <Response [400]>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 272, in information
    data = self.get(SynoDSMInformation.API_KEY, "getinfo")
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 169, in get
    return self._request("GET", api, method, params, **kwargs)
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 183, in _request
    self.discover_apis()
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 104, in discover_apis
    self._apis = self.get(self.API_INFO, "query")["data"]
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 169, in get
    return self._request("GET", api, method, params, **kwargs)
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 213, in _request
    response = self._execute_request(request_method, url, params=params, **kwargs)
  File "<dir>/home-assistant/venv/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 252, in _execute_request
    raise SynologyDSMRequestException(exp)
synology_dsm.exceptions.SynologyDSMRequestException: RequestException = Bad Request
```

**Comment by raman325** [comment]
doh when testing forgot to set the "use HTTPS" parameter to true. Got it to work now directly. Will keep troubleshooting the HA issue and will post as I learn more
