### ISSUE TITLE
2SA auth expire after some days

### ISSUE THREAD

**Issue by chemelli74** [ProtoThis/python-synology#49]
Everything was working fine for some days, but suddenly:

```
2020-05-09 16:14:37 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry homenas for synology_dsm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 76, in async_setup_entry
    await api.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 149, in async_setup
    await self._hass.async_add_executor_job(self._fetch_device_configuration)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 158, in _fetch_device_configuration
    self.information = self.dsm.information
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 280, in information
    data = self.get(SynoDSMInformation.API_KEY, "getinfo")
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 173, in get
    return self._request("GET", api, method, params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 191, in _request
    self.login()
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 161, in login
    data = self.get(SynoDSMInformation.API_KEY, "getinfo")
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 173, in get
    return self._request("GET", api, method, params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 230, in _request
    return self._request(request_method, api, method, params, False)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 191, in _request
    self.login()
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 148, in login
    raise switcher.get(result["error"]["code"], SynologyDSMLoginFailedException)
synology_dsm.exceptions.SynologyDSMLogin2SARequiredException: Two-step authentication required for account: homeassistant
```

I fear device token somehow expire after some days/weeks.

Simone

**Comment by Quentame** [comment]
Do you know how many days ?

**Comment by chemelli74** [comment]
Unfortunately not, wild guess is from release date of HA build with 2SA vanilla support and May, 9th when the error happened.

Simone

**Comment by chemelli74** [comment]
One month passed, and never experienced this issue again.
Fingers crossed.

Simone

**Comment by chemelli74** [comment]
Unfortunately, here it is:

```
2020-06-22 18:21:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry homenas for synology_dsm
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 161, in async_setup_entry
    await api.async_setup()
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 253, in async_setup
    await self._hass.async_add_executor_job(self._fetch_device_configuration)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/synology_dsm/__init__.py", line 311, in _fetch_device_configuration
    self.information = self.dsm.information
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 321, in information
    data = self.get(SynoDSMInformation.API_KEY, "getinfo")
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 177, in get
    return self._request("GET", api, method, params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 195, in _request
    self.login()
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 165, in login
    data = self.get(SynoDSMInformation.API_KEY, "getinfo")
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 177, in get
    return self._request("GET", api, method, params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 234, in _request
    return self._request(request_method, api, method, params, False)
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 195, in _request
    self.login()
  File "/usr/local/lib/python3.7/site-packages/synology_dsm/synology_dsm.py", line 152, in login
    raise switcher.get(result["error"]["code"], SynologyDSMLoginFailedException)
synology_dsm.exceptions.SynologyDSMLogin2SARequiredException: {'api': 'SYNO.API.Auth', 'code': 403, 'reason': 'One time password not specified', 'details': 'Two-step authentication required for account: homeassistant'}
```

Can you trap it into a notification and ask for a relogin ?
Thank you,

Simone

**Comment by chemelli74** [comment]
Hi @Quentame, do you think a notification to relogin can be implemented ?

Like [Alexa Media Player](https://github.com/custom-components/alexa_media_player/blob/dev/custom_components/alexa_media/config_flow.py) did for the same issue.

Thank you in advance,

Simone

**Comment by Quentame** [comment]
Hi !

Yes I can, but I have huge issues on Linky integration for now, so it will pass after, sorry.

Or you can try and I will review.

Thanks

**Comment by chemelli74** [comment]
I bet the issue is related to the 2 instances I run on docker.

Maybe ["device_name"](https://github.com/ProtoThis/python-synology/blob/27379e7cd6cfdd24abc2da03ed289b34f3eb96a7/synology_dsm/synology_dsm.py#L138) can be updated including [HA instance name](https://github.com/home-assistant/core/blob/f286992b1007588ae1221352883259393947fdfe/homeassistant/config.py#L495).

What you think ?

Simone

**Comment by chemelli74** [comment]
Hi @Quentame, do you mind checking this one ? ;-)

Thx,

Simone

**Comment by chemelli74** [comment]
Issue is linked to my specific scenario, 2 ha instances (prod/test) on container with `--net=host`.
So with same ip address.

Nothing that can be fixed in the code :-(

Simone
